/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2020-01-21 04:38:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._005f09_005frentcar;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _11_005fcarOptionSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		int no = Integer.parseInt(request.getParameter("no"));
		// 수량
		int qty = Integer.parseInt(request.getParameter("qty"));
		// 이미지
		String img = request.getParameter("img");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"01_main.jsp?center=12_carReserveResult.jsp\"\r\n");
      out.write("\t\tmethod=\"post\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr height=\"100\">\r\n");
      out.write("\t\t\t\t<td align=\"center\" colspan=\"3\"><font size=\"6\" color=\"gray\">\r\n");
      out.write("\t\t\t\t\t\t옵션 선택</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td rowspan=\"7\" width=\"500\" align=\"center\"><img alt=\"\"\r\n");
      out.write("\t\t\t\t\tsrc=\"_09_imgCar/");
      out.print(img);
      out.write("\" width=\"450\"></td>\r\n");
      out.write("\t\t\t\t<td width=\"250\" align=\"center\">대여기간</td>\r\n");
      out.write("\t\t\t\t<td width=\"250\" align=\"center\"><select name=\"dday\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">1일</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">2일</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">3일</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">4일</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">5일</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"6\">6일</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"7\">7일</option>\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"250\" align=\"center\">대여일</td>\r\n");
      out.write("\t\t\t\t<td width=\"250\" align=\"center\"><input type=\"date\" name=\"rday\" id=\"today\"\r\n");
      out.write("\t\t\t\t\tsize=\"15\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\t//document.getElementById(\"today\").value= new Date().toISOString().substring(0,10);\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"250\" align=\"center\">보험적용</td>\r\n");
      out.write("\t\t\t\t<td width=\"250\" align=\"center\"><select name=\"usein\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">적용(1일 1만원)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">비적용</option>\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"250\" align=\"center\">Wifi 적용</td>\r\n");
      out.write("\t\t\t\t<td width=\"250\" align=\"center\"><select name=\"usewifi\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">적용(1일 1만원)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">비적용</option>\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"250\" align=\"center\">네비게이션 적용</td>\r\n");
      out.write("\t\t\t\t<td width=\"250\" align=\"center\"><select name=\"usenavi\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">적용(무료)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">비적용</option>\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"250\" align=\"center\">베이비시트 적용</td>\r\n");
      out.write("\t\t\t\t<td width=\"250\" align=\"center\"><select name=\"useseat\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">적용(1일 1만원)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">비적용</option>\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\" colspan=\"2\"><input type=\"hidden\" name=\"no\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(no);
      out.write("\"> <input type=\"hidden\" name=\"qty\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(qty);
      out.write("\"> <input type=\"submit\" value=\"차량예약하기\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
